import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'intro',
        'overview',
        'get-started',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/metadata-fundamentals',
        'concepts/types-of-assets',
        'concepts/structural-organization',
        'concepts/linking-vs-embedding',
        'concepts/validation',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples/overview',
        'examples/3d-model',
        'examples/avatar',
        'examples/environment',
        'examples/scene',
      ],
    },
    {
      type: 'category',
      label: 'Implementation',
      items: [
        'implementation/overview',
        'implementation/getting-started',
        'implementation/assets',
        'implementation/nfts',
        'implementation/composable',
        'implementation/best-practices',
        'implementation/metadata-profiles',
        'implementation/standards-implementation',
      ],
    },
    {
      type: 'category',
      label: 'Integration Profiles',
      items: [
        'integration-profiles/overview',
        'integration-profiles/unreal',
        'integration-profiles/unity',
        'integration-profiles/web',
      ],
    },
    {
      type: 'category',
      label: 'Embedding',
      items: [
        'embedding/overview',
        'embedding/json-ld',
        'embedding/3d-model-embedding',
        'embedding/image-embedding',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        'community/contribute',
        'community/partners',
        'community/events',
        'community/forum',
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [
        'tools/overview',
        'tools/validation',
        'tools/schema-generator',
        'tools/metadata-explorer',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/cross-standard',
        'guides/migration',
        'guides/marketplaces',
      ],
    },
  ],
};

export default sidebars;
