name: Standards Integration

on:
  pull_request:
    paths:
      - 'docs/standards/**'
      - 'docs/contributors/standards-organizations/**'
      - '.github/ISSUE_TEMPLATE/standards-integration.md'
  issues:
    types: [opened, edited]
    paths:
      - '.github/ISSUE_TEMPLATE/standards-integration.md'

jobs:
  validate-standards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate JSON-LD Examples
        run: |
          npm install -g jsonld
          find docs/standards -name "*.json" -exec jsonld validate {} \;
          
      - name: Check Documentation Structure
        run: |
          # Verify required sections exist
          if [ ! -f "docs/standards/${{ github.event.issue.title }}.md" ]; then
            echo "Missing standards documentation file"
            exit 1
          fi
          
  notify-maintainers:
    needs: validate-standards
    runs-on: ubuntu-latest
    steps:
      - name: Notify Maintainers
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['standards-review']
            })
            
  welcome-contributor:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Welcome New Contributor
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thank you for your interest in integrating your standard with MVMD! A maintainer will review your submission shortly. In the meantime, please ensure you have provided all required information in the template.'
            }) 